# Generated by Django 4.2.6 on 2023-10-08 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date', '-time']},
        ),
        migrations.RemoveField(
            model_name='event',
            name='organizer',
        ),
    ]
