# Generated by Django 4.2.7 on 2023-11-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_event_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Politics', 'Politics'), ('Technology', 'Technology'), ('Science', 'Science'), ('Socials', 'Socials'), ('Entertainment', 'Entertainment'), ('Others', 'Others')], max_length=300),
        ),
    ]
